apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: service-a
  namespace: argocd
spec:
  generators:
    - list:
        elements:
        - cluster: staging
          url: https://kubernetes.default.svc
          alias: s-g
        - cluster: production
          url: https://kubernetes.default.svc
          alias: p-c
  template:
    metadata:
      name: '{{alias}}-service-a'
    spec:
      project: default
      sources:
        - repoURL: https://charts.bitnami.com/bitnami
          targetRevision: 15.5.3
          chart: nginx
          helm:
            releaseName: '{{alias}}-service-a'
            valueFiles:
              - '$values/team-a/service-a/values-{{cluster}}.yaml'
        - repoURL: https://github.com/ecojuntak/argo-appset-test
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{url}}'
        namespace: default
